# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'temurin'

    # Ejecuta Maven para compilar y ejecutar las pruebas
    - name: Build with Maven
      run: mvn clean install -DskipTests=false

    # Ejecuta los tests (opcional, puedes separar esta tarea si lo prefieres)
    - name: Run tests with Maven
      run: mvn test

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "insw"  # replace with your app name
          heroku_email: "carlos.ramirez.lizan@gmail.com"  # replace with your Heroku email
          branch: main
          dontuseforce: false
          dontautocreate: false
          usedocker: false
          docker_heroku_process_type: web
          delay: 0
          rollbackonhealthcheckfailed: false
          justlogin: false
